### ISSUE TITLE
May I ask you what static server you are using ？

### ISSUE THREAD

**Issue by Ticsmtc** [danloh/rut-server-rust#5]
I'm learning about this project, but I have a question about how you can make  actix-web service a Single Page Vue application, which I don't see in the code. This requires a static server. Do you use anything else as a static server? 😊

**Comment by danloh** [comment]
nginx;

and actix-web can serve static file, see also: https://github.com/danloh/toplog/blob/8e9ff5f2bd8f639aa81d0aef3a50621bfe2a9fe3/src/lib.rs#L176

**Comment by Ticsmtc** [comment]
thanks
